spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

line:
  private-key: |
    ${LINE_PRIVATE_KEY}
  kid: ${LINE_KID}
  channel-id: ${LINE_CHANNEL_ID}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  valid-seconds: ${JWT_VALID_SECONDS}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: C:/wooper/logs/wooper.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n%ex{20}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n%ex{20}"